# Generated by Django 3.1.7 on 2021-03-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Skill',
        ),
    ]
